// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// AUTO-GENERATED FILE.
//
// This file is auto-generated by Ballerina.
// Developers are allowed to modify this file as per the requirement.

import ballerinax/health.fhir.r5;

final r5:ResourceAPIConfig  genomicstudyApiConfig = {
    resourceType: "GenomicStudy",
    profiles: [
            "http://hl7.org/fhir/StructureDefinition/GenomicStudy"
        

    ],
    defaultProfile: (),
    searchParameters: [
        {
        name: "identifier",
        active: true,
        information: {
            description: "Identifiers for the Study",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/GenomicStudy-identifier"
        }
    },

        {
        name: "status",
        active: true,
        information: {
            description: "The status of the study",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/GenomicStudy-status"
        }
    },

        {
        name: "subject",
        active: true,
        information: {
            description: "Who the study is about",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/GenomicStudy-subject"
        }
    },

        {
        name: "focus",
        active: true,
        information: {
            description: "What the genomic study analysis is about, when it is not about the subject of record",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/GenomicStudy-focus"
        }
    },

        {
        name: "patient",
        active: true,
        information: {
            description: "Who the study is about",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/GenomicStudy-patient"
        }
    }

    ],
    operations: [

    ],
    serverConfig: (),
    authzConfig: ()
};
