// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).

// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
// AUTO-GENERATED FILE.
//
// This file is auto-generated by Ballerina.
// Developers are allowed to modify this file as per the requirement.

import ballerinax/health.fhir.r5;

final r5:ResourceAPIConfig  molecularsequenceApiConfig = {
    resourceType: "MolecularSequence",
    profiles: [
            "http://hl7.org/fhir/StructureDefinition/MolecularSequence"
        

    ],
    defaultProfile: (),
    searchParameters: [
        {
        name: "identifier",
        active: true,
        information: {
            description: "[MolecularSequence](molecularsequence.html): The unique identity for a particular sequence",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/clinical-identifier"
        }
    },

        {
        name: "patient",
        active: true,
        information: {
            description: "[MolecularSequence](molecularsequence.html): The subject that the sequence is about",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/clinical-patient"
        }
    },

        {
        name: "type",
        active: true,
        information: {
            description: "[MolecularSequence](molecularsequence.html): Amino Acid Sequence/ DNA Sequence / RNA Sequence",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/clinical-type"
        }
    },

        {
        name: "focus",
        active: true,
        information: {
            description: "What the molecular sequence is about, when it is not about the subject of record",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/MolecularSequence-focus"
        }
    },

        {
        name: "subject",
        active: true,
        information: {
            description: "The subject that the sequence is about",
            builtin: false,
            documentation: "http://hl7.org/fhir/SearchParameter/MolecularSequence-subject"
        }
    }

    ],
    operations: [

    ],
    serverConfig: (),
    authzConfig: ()
};
