[package]
org = "ballerinax"
name = "health.fhir.r4.uscore501.patient"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "r4", "Patient", "health.fhir.r4.uscore501"]
template = true
