[package]
org = "ballerinax"
name = "health.fhir.r5.international500.patient"
version = "1.0.0"
distribution = "2201.12.3"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "r5", "Patient", "health.fhir.r5.international500"]
template = true
